export const IMAGES = {

	user: require('../assets/images/user.png'),
	logo: require('../assets/images/logo.png'),
	bottomtab: require('../assets/images/bottomtab.png'),
	card: require('../assets/images/card.png'),
	card1: require('../assets/images/card1.png'),
	sun: require('../assets/images/icons/sun.png'),
	chat: require('../assets/images/icons/chat.png'),
	ads: require('../assets/images/icons/ads.png'),
	profile: require('../assets/images/icons/user3.png'),
	user2: require('../assets/images/icons/user.png'),
	card2: require('../assets/images/icons/card2.png'),
	map: require('../assets/images/icons/map.png'),
	map2: require('../assets/images/icons/map2.png'),
	bell2: require('../assets/images/icons/bell2.png'),
	comment: require('../assets/images/icons/comment.png'),
	star: require('../assets/images/icons/star.png'),
	star2: require('../assets/images/icons/star2.png'),
	star3: require('../assets/images/icons/star3.png'),
	star4: require('../assets/images/icons/star4.png'),
	star5: require('../assets/images/icons/Star5.png'),
	star6: require('../assets/images/icons/Star6.png'),
	star7: require('../assets/images/icons/Star7.png'),
	translation: require('../assets/images/icons/translation.png'),
	google2: require('../assets/images/icons/google2.png'),
	arrowleft: require('../assets/images/icons/arrow-left.png'),
	home: require('../assets/images/icons/home.png'),
	document: require('../assets/images/icons/document.png'),
	shopping: require('../assets/images/icons/shopping.png'),
	heart2: require('../assets/images/icons/heart2.png'),
	bell: require('../assets/images/icons/bell.png'),
	search: require('../assets/images/icons/search.png'),
	close: require('../assets/images/icons/close.png'),
	delete: require('../assets/images/icons/delete.png'),
	check: require('../assets/images/icons/check.png'),
	check2: require('../assets/images/icons/check2.png'),
	write: require('../assets/images/icons/write.png'),
	shop: require('../assets/images/icons/shop.png'),
	rightarrow: require('../assets/images/icons/rightarrow.png'),
	plus: require('../assets/images/icons/plus.png'),
	shieldcheck: require('../assets/images/icons/shieldcheck.png'),
	bank: require('../assets/images/icons/bank.png'),
	folder: require('../assets/images/icons/folder.png'),
	payment: require('../assets/images/icons/payment.png'),
	dollar: require('../assets/images/icons/dollar.png'),
	downaeeowsmall: require('../assets/images/icons/downaeeowsmall.png'),
	call: require('../assets/images/icons/call.png'),
	send: require('../assets/images/icons/send.png'),
	happy: require('../assets/images/icons/happy.png'),
	phone: require('../assets/images/icons/phone.png'),
	volume: require('../assets/images/icons/volume.png'),
	audio: require('../assets/images/icons/audio.png'),
	audiomute: require('../assets/images/icons/audiomute.png'),
	components: require('../assets/images/icons/components.png'),
	order: require('../assets/images/icons/order.png'),
	producta: require('../assets/images/icons/producta.png'),
	logout: require('../assets/images/icons/logout.png'),
	grid: require('../assets/images/icons/grid.png'),
	list: require('../assets/images/icons/list.png'),
	arrowup: require('../assets/images/icons/arrowup.png'),
	filter: require('../assets/images/icons/filter.png'),
	filter2: require('../assets/images/icons/filter2.png'),
	moon: require('../assets/images/icons/moon.png'),
	facebook: require('../assets/images/icons/facebook.png'),
	grid2: require('../assets/images/icons/grid2.png'),
	thumbsup: require('../assets/images/icons/thumbs-up.png'),
	datepicker: require('../assets/images/icons/datepicker.png'),
	search2: require('../assets/images/icons/search2.png'),
	calendar: require('../assets/images/icons/calendar.png'),
	menu: require('../assets/images/icons/menu.png'),
	time: require('../assets/images/icons/time.png'),

	item4: require('../assets/images/item/pic4.png'),
	item5: require('../assets/images/item/pic5.png'),
	item6: require('../assets/images/item/pic6.png'),
	item7: require('../assets/images/item/pic7.png'),
	item11: require('../assets/images/item/pic11.png'),
	item12: require('../assets/images/item/pic12.png'),
	item13: require('../assets/images/item/pic13.png'),
	item14: require('../assets/images/item/pic14.png'),
	item15: require('../assets/images/item/pic15.png'),
	item16: require('../assets/images/item/pic16.png'),
	item17: require('../assets/images/item/pic17.png'),
	item18: require('../assets/images/item/pic18.png'),
	item20: require('../assets/images/item/pic20.png'),
	item21: require('../assets/images/item/pic21.png'),
	item22: require('../assets/images/item/pic22.png'),
	item23: require('../assets/images/item/pic23.png'),

	itemDetails7: require('../assets/images/itemDetails/pic7.png'),
	itemDetails8: require('../assets/images/itemDetails/pic8.png'),
	itemDetails9: require('../assets/images/itemDetails/pic9.png'),
	itemDetails10: require('../assets/images/itemDetails/pic10.png'),
	itemDetails11: require('../assets/images/itemDetails/pic11.png'),

	banner1: require('../assets/images/banner/banner1.png'),

	small1: require('../assets/images/small/pic5.png'),
	small2: require('../assets/images/small/pic6.png'),
	small3: require('../assets/images/small/pic7.png'),
	small4: require('../assets/images/small/pic8.png'),
	small5: require('../assets/images/small/pic9.png'),
	small6: require('../assets/images/small/pic10.png'),

	small7: require('../assets/images/small/pic1.jpg'),
	small8: require('../assets/images/small/pic2.jpg'),
	small9: require('../assets/images/small/pic3.jpg'),
	small10: require('../assets/images/small/pic4.jpg'),

	product5: require('../assets/images/product/pic5.png'),
	product6: require('../assets/images/product/pic6.png'),
	product7: require('../assets/images/product/pic7.png'),

	ads1: require('../assets/images/ads/banner1.png'),
	ads2: require('../assets/images/ads/banner2.png'),
	ads3: require('../assets/images/ads/banner3.png'),

	onboardingpic1: require('../assets/images/onboarding/pic1.png'),
	onboardingVector: require('../assets/images/onboarding/Vector.png'),
	onboardingVector2: require('../assets/images/onboarding/Vector2.png'),


}